export type LegalDocumentId = 'privacy-policy' | 'terms-of-service';

export type LegalDocument = {
  id: LegalDocumentId;
  title: string;
  markdown: string;
};

// Keep this copy aligned with apps/react-native/core/legal/documents.ts.
const legalDocuments: Record<LegalDocumentId, LegalDocument> = {
  'privacy-policy': {
    id: 'privacy-policy',
    title: 'Privacy Policy',
    markdown: `# Limbo Health Privacy Policy

Last updated: April 5, 2026

> Working draft for publication. This document should be reviewed by counsel before it is published or linked from App Store Connect.

This Privacy Policy explains how Limbo Health collects, uses, stores, and shares information when you use the Limbo Health mobile app, website, and related services.

Limbo Health is designed to help people organize personal medical information, prepare medical-records requests, and manage encrypted personal health records with a strong emphasis on patient self-custody.

## 1. Scope

This Privacy Policy applies to:

- the Limbo Health mobile app
- limbohealth.com
- limbo.health
- related support, authentication, storage, and records-request services we operate

## 2. Information We May Collect

### Information you provide directly

Depending on how you use Limbo Health, you may provide:

- account information, such as your name and email address
- sign-in information from Apple, Google, or another supported authentication provider
- records-request profile information, such as full name, date of birth, last four digits of Social Security number, phone number, email address, and mailing address
- form answers, signatures, ID images, and other materials you add to a records-request workflow
- encrypted binder content and attachments you choose to create, store, or sync
- support communications you send to us

### Information from third-party sign-in providers

If you sign in with Apple or Google, we may receive information such as:

- your name
- your email address
- provider-specific account identifiers

We receive only the information those providers make available to us for authentication and account setup.

### Device permissions

The app may request access to:

- camera
- photo library
- microphone

We use these permissions to support features such as ID capture, document attachments, photo-based record capture, and audio notes.

### Technical and operational information

We may process limited technical information needed to operate, secure, and troubleshoot the service, such as:

- authentication/session information
- device or app version information
- network and request metadata
- crash information generated by the operating system or app runtime

## 3. Information We Try to Keep on Your Device

Limbo Health is designed to keep sensitive information on your device where possible.

Current product behavior and internal specs indicate that the following are intended to remain on-device unless you choose to transmit them through a workflow:

- your records-request identity profile
- portal credentials stored in the app
- local encryption keys
- binder content before any optional sync
- locally captured photos, audio, and generated files before you share or upload them

## 4. Encrypted Storage and Sync

Some Limbo Health features allow you to keep encrypted personal medical records and optionally sync them to Limbo-operated infrastructure.

When you use encrypted binder features:

- encryption is intended to happen on-device before sync
- our service may store encrypted content and limited operational metadata
- metadata such as file size, timestamps, repository identifiers, and access patterns may still be visible to us and our infrastructure providers even when the content itself is encrypted

## 5. How We Use Information

We may use information we process to:

- authenticate users and maintain accounts
- save and restore your app state
- prefill medical-records request forms and workflows
- fetch hospital-specific records-request packets and instructions
- generate completed request PDFs
- enable encrypted storage and sync features
- respond to support requests
- secure, maintain, and improve the service
- comply with legal obligations and enforce our Terms of Service

## 6. When We Share Information

We do not sell or rent your personal information.

We may share information in the following circumstances:

- with service providers that help us operate the service, such as authentication, hosting, storage, and infrastructure vendors
- with hospitals, health systems, or other recipients when you choose to submit or share a records request
- with Apple, Google, or other sign-in providers when required for authentication
- if required by law, regulation, subpoena, court order, or other legal process
- in connection with a merger, acquisition, financing, or sale of assets

## 7. Data Retention

We retain information for as long as reasonably necessary to:

- provide the service
- maintain account and security records
- support encrypted sync and storage features
- comply with legal obligations
- resolve disputes and enforce our agreements

Information stored only on your device may remain there until you delete it, remove the app, reset local app state, or otherwise clear local storage.

## 8. Your Choices

Depending on the feature, you may be able to:

- update profile and account information in the app
- manage device permissions through iOS settings
- delete your account from within the app
- choose whether to sync encrypted content to Limbo-operated services
- choose whether to share generated PDFs by email, AirDrop, print, mail, or another method

## 9. Security

We use administrative, technical, and organizational measures intended to protect information we process. No method of transmission, storage, or processing is completely secure, and we cannot guarantee absolute security.

Because Limbo Health includes self-custody and encryption features, you are also responsible for:

- securing access to your device
- protecting your sign-in credentials
- safeguarding any encryption keys or exported key material

## 10. Children's Privacy

Limbo Health is not intended to be a general-purpose app for children to use independently. If you use the service on behalf of another person, including a minor, you are responsible for having appropriate authority to do so.

## 11. Changes to This Privacy Policy

We may update this Privacy Policy from time to time. If we make material changes, we may update the date at the top of this page and take other steps as appropriate.

## 12. Contact Us

If you have questions about this Privacy Policy, contact:

- Email: [support@limbo.health](mailto:support@limbo.health)
- Website: [limbohealth.com](https://limbohealth.com)
- Support: [Support](mailto:support@limbo.health)`,
  },
  'terms-of-service': {
    id: 'terms-of-service',
    title: 'Terms of Service',
    markdown: `# Limbo Health Terms of Service

Last updated: April 5, 2026

> Working draft for publication. This document should be reviewed by counsel before it is published or used as a custom end-user agreement.

These Terms of Service govern your access to and use of the Limbo Health mobile app, website, and related services.

By using Limbo Health, you agree to these Terms.

## 1. The Service

Limbo Health is a patient-focused product designed to help users:

- organize and manage personal medical information
- prepare and share medical-records requests
- generate filled request PDFs for supported workflows
- maintain encrypted personal medical records and related attachments

## 2. Eligibility and Authority

You may use Limbo Health only if you can form a binding agreement under applicable law.

If you use Limbo Health on behalf of another person, including as a parent, guardian, caregiver, or authorized representative, you represent that you have the authority to do so.

## 3. Not Medical Advice or Emergency Care

Limbo Health is an administrative and information-management tool.

Limbo Health does not:

- provide medical advice
- diagnose conditions
- recommend treatment
- replace a doctor, hospital, lawyer, or emergency service

Do not use Limbo Health for emergencies. If you believe you are experiencing a medical emergency, call emergency services immediately.

## 4. Accounts and Sign-In

You may be able to sign in using supported authentication methods such as Apple or Google.

You are responsible for:

- keeping your device secure
- maintaining the confidentiality of your login credentials
- all activity that occurs through your account unless caused by our own misconduct

## 5. Self-Custody and Encryption Keys

Limbo Health is built around patient self-custody.

If you use encryption, local key storage, or encrypted binder features:

- you are responsible for safeguarding your device and key material
- losing access to your device or encryption keys may make some data permanently inaccessible
- Limbo Health does not guarantee recovery of encrypted content if required keys are lost or unavailable

## 6. Your Content

You retain your rights in the information, documents, and files you submit, generate, or store through Limbo Health.

You grant Limbo Health a limited license to host, process, transmit, back up, and otherwise use that content only as necessary to operate and improve the service, comply with law, and enforce these Terms.

You represent that:

- you have the rights and authority needed to use the content with Limbo Health
- the information you provide is accurate to the best of your knowledge
- your use of the service does not violate applicable law or another person's rights

## 7. Records-Request Workflows

Limbo Health may help you search supported hospital systems, answer questions, generate records-request PDFs, and share or submit those materials.

You understand and agree that:

- hospitals and third parties decide whether to accept, process, or reject a request
- hospital instructions, workflows, and requirements may change
- you are responsible for reviewing the final request before sending it
- you are responsible for choosing how to send it, including email, share, AirDrop, mail, fax, or portal submission
- Limbo Health does not guarantee that a request will be received, accepted, or fulfilled

## 8. Acceptable Use

You may not use Limbo Health to:

- break the law
- submit false, fraudulent, or misleading requests
- infringe another person's rights or privacy
- interfere with or disrupt the service
- attempt unauthorized access to accounts, devices, systems, or data
- reverse engineer, scrape, or misuse the service beyond what applicable law allows

## 9. Availability and Changes

We may add, change, suspend, or remove features at any time.

We do not guarantee that the service, any hospital workflow, or any third-party integration will always be available, accurate, or uninterrupted.

## 10. Termination

You may stop using Limbo Health at any time.

We may suspend or terminate access if we believe:

- you violated these Terms
- your use creates legal, security, or operational risk
- we are required to do so by law

Termination does not automatically delete local information stored on your device.

## 11. Disclaimers

To the fullest extent permitted by law, Limbo Health is provided on an \`as is\` and \`as available\` basis.

We disclaim warranties of any kind, whether express or implied, including implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement.

## 12. Limitation of Liability

To the fullest extent permitted by law, Limbo Health and its affiliates, officers, employees, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of data, goodwill, revenues, profits, or business opportunities arising out of or related to your use of the service.

Nothing in these Terms excludes liability that cannot be excluded under applicable law.

## 13. Changes to These Terms

We may update these Terms from time to time. If we make material changes, we may update the date at the top of this page and take other steps as appropriate.

Your continued use of Limbo Health after updated Terms become effective means you accept the revised Terms.

## 14. Contact

If you have questions about these Terms, contact:

- Email: [support@limbo.health](mailto:support@limbo.health)
- Website: [limbohealth.com](https://limbohealth.com)
- Privacy Policy: [Privacy Policy](/privacy-policy)
- Support: [Support](mailto:support@limbo.health)`,
  },
};

export function getLegalDocument(id: LegalDocumentId): LegalDocument {
  return legalDocuments[id];
}
