create extension if not exists citext;

create table if not exists roles (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  name text,
  slug text,
  is_admin boolean,
  appointments integer,
  customers integer,
  services integer,
  users integer,
  system_settings integer,
  user_settings integer,
  webhooks integer,
  blocked_periods integer
);

create index if not exists roles_slug_idx on roles (slug);
create unique index if not exists roles_id_unique_idx on roles (id);

create table if not exists users (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  first_name text,
  last_name text,
  email citext,
  mobile_number text,
  phone_number text,
  address text,
  city text,
  state text,
  zip_code text,
  notes text,
  timezone text default 'UTC',
  language text default 'english',
  is_private boolean default false,
  id_roles integer references roles(id) on delete cascade on update cascade,
  nostr_pubkey text unique,
  ed25519_pubkey text,
  encrypted_ed25519_privkey text
);

create index if not exists users_id_roles_idx on users (id_roles);
create index if not exists users_email_idx on users (email);
create unique index if not exists users_nostr_pubkey_unique_idx
  on users (nostr_pubkey)
  where nostr_pubkey is not null;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'users'::regclass
       and contype = 'p'
  ) then
    alter table users add constraint users_pkey primary key (id);
  end if;
end $$;

create table if not exists oauth_connections (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade on update cascade,
  provider text not null,
  provider_user_id text not null,
  provider_email citext,
  access_token text,
  refresh_token text,
  token_expires_at timestamp,
  created_at timestamp default current_timestamp,
  updated_at timestamp default current_timestamp,
  constraint oauth_connections_provider_user_unique unique (provider, provider_user_id)
);

create index if not exists oauth_connections_user_id_idx on oauth_connections (user_id);
create index if not exists oauth_connections_provider_idx on oauth_connections (provider);
create unique index if not exists oauth_connections_id_unique_idx on oauth_connections (id);
create unique index if not exists oauth_connections_provider_user_unique_idx
  on oauth_connections (provider, provider_user_id);

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'oauth_connections'::regclass
       and contype = 'p'
  ) then
    alter table oauth_connections add constraint oauth_connections_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'oauth_connections_user_id_fkey'
  ) then
    alter table oauth_connections
      add constraint oauth_connections_user_id_fkey
      foreign key (user_id) references users(id)
      on delete cascade on update cascade;
  end if;
end $$;

create table if not exists user_settings (
  id_users integer primary key references users(id) on delete cascade on update cascade,
  username text,
  password text,
  salt text,
  working_plan text,
  working_plan_exceptions text,
  notifications boolean,
  google_sync boolean,
  google_calendar text,
  caldav_sync boolean default false,
  caldav_url text,
  caldav_username text,
  caldav_password text,
  sync_past_days integer default 30,
  sync_future_days integer default 90,
  calendar_view text default 'default'
);

create table if not exists repositories (
  id text primary key,
  description text,
  repo_type text default 'medical-history',
  owner_user_id integer not null references users(id) on delete cascade,
  created_at timestamp default current_timestamp,
  updated_at timestamp default current_timestamp
);

create index if not exists repositories_owner_idx on repositories (owner_user_id);
create unique index if not exists repositories_id_unique_idx on repositories (id);

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'repositories'::regclass
       and contype = 'p'
  ) then
    alter table repositories add constraint repositories_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'repositories_owner_user_id_fkey'
  ) then
    alter table repositories
      add constraint repositories_owner_user_id_fkey
      foreign key (owner_user_id) references users(id)
      on delete cascade;
  end if;
end $$;

create table if not exists repository_access (
  id integer generated by default as identity primary key,
  repo_id text not null references repositories(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  access_level text not null default 'read-only' check (access_level in ('admin', 'read-write', 'read-only')),
  created_at timestamp default current_timestamp,
  constraint repository_access_repo_user_unique unique (repo_id, user_id)
);

create index if not exists repository_access_user_idx on repository_access (user_id);
create unique index if not exists repository_access_repo_user_unique_idx
  on repository_access (repo_id, user_id);
create unique index if not exists repository_access_id_unique_idx on repository_access (id);

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'repository_access'::regclass
       and contype = 'p'
  ) then
    alter table repository_access add constraint repository_access_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'repository_access_repo_id_fkey'
  ) then
    alter table repository_access
      add constraint repository_access_repo_id_fkey
      foreign key (repo_id) references repositories(id)
      on delete cascade;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'repository_access_user_id_fkey'
  ) then
    alter table repository_access
      add constraint repository_access_user_id_fkey
      foreign key (user_id) references users(id)
      on delete cascade;
  end if;
end $$;

create table if not exists scan_sessions (
  id integer generated by default as identity primary key,
  session_token text not null unique,
  staging_repo_id text not null,
  patient_user_id integer not null references users(id) on delete cascade,
  created_at timestamp default current_timestamp,
  expires_at timestamp not null,
  is_revoked boolean default false
);

create index if not exists scan_sessions_token_idx on scan_sessions (session_token);
create index if not exists scan_sessions_expires_idx on scan_sessions (expires_at);
create index if not exists scan_sessions_staging_repo_idx on scan_sessions (staging_repo_id);
create unique index if not exists scan_sessions_id_unique_idx on scan_sessions (id);
create unique index if not exists scan_sessions_token_unique_idx on scan_sessions (session_token);

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'scan_sessions'::regclass
       and contype = 'p'
  ) then
    alter table scan_sessions add constraint scan_sessions_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'scan_sessions_patient_user_id_fkey'
  ) then
    alter table scan_sessions
      add constraint scan_sessions_patient_user_id_fkey
      foreign key (patient_user_id) references users(id)
      on delete cascade;
  end if;
end $$;

create table if not exists provider_profiles (
  user_id integer primary key references users(id) on delete cascade,
  username citext unique,
  bio text,
  profile_pic_url text,
  year_of_birth integer,
  place_of_birth text,
  gender text,
  languages jsonb,
  first_name text,
  last_name text,
  suffix text,
  license_number text,
  license_state text default 'TX',
  license_issued_date date,
  license_expiration_date date,
  registration_status text,
  registration_date date,
  method_of_licensure text,
  medical_school text,
  graduation_year integer,
  degree_type text,
  primary_specialty text,
  secondary_specialty text,
  board_certifications jsonb,
  created_at timestamp default current_timestamp,
  updated_at timestamp default current_timestamp,
  working_plan jsonb,
  timezone text default 'America/Chicago'
);

create index if not exists provider_profiles_license_idx on provider_profiles (license_number);

create table if not exists service_categories (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  name text,
  description text
);

create table if not exists services (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  name text,
  duration integer,
  price numeric(10, 2),
  currency text,
  description text,
  color text default '#7cbae8',
  location text,
  availabilities_type text default 'flexible',
  attendants_number integer default 1,
  is_private boolean default false,
  id_service_categories integer references service_categories(id) on delete set null on update cascade
);

create index if not exists services_service_category_idx on services (id_service_categories);

create table if not exists services_providers (
  id_users integer not null references users(id) on delete cascade on update cascade,
  id_services integer not null references services(id) on delete cascade on update cascade,
  primary key (id_users, id_services)
);

create index if not exists services_providers_service_idx on services_providers (id_services);

create table if not exists appointments (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  book_datetime timestamp,
  start_datetime timestamp,
  end_datetime timestamp,
  location text,
  notes text,
  hash text,
  color text default '#7cbae8',
  status text default '',
  is_unavailability boolean not null default false,
  id_users_provider integer references users(id) on delete cascade on update cascade,
  id_users_customer integer references users(id) on delete cascade on update cascade,
  id_services integer references services(id) on delete cascade on update cascade,
  id_google_calendar text,
  id_caldav_calendar text,
  meeting_link text
);

create index if not exists appointments_provider_idx on appointments (id_users_provider);
create index if not exists appointments_customer_idx on appointments (id_users_customer);
create index if not exists appointments_service_idx on appointments (id_services);

create table if not exists blocked_periods (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  name text,
  start_datetime timestamp,
  end_datetime timestamp,
  notes text
);

create table if not exists invoices (
  id integer generated by default as identity primary key,
  appointment_id integer not null references appointments(id) on delete cascade on update cascade,
  payment_request text not null,
  amount_sats integer not null,
  invoice_hash text not null,
  status text default 'pending',
  created_at timestamp,
  paid_at timestamp
);

create index if not exists invoices_invoice_hash_idx on invoices (invoice_hash);
create index if not exists invoices_appointment_id_idx on invoices (appointment_id);

create table if not exists secretaries_providers (
  id_users_secretary integer not null references users(id) on delete cascade on update cascade,
  id_users_provider integer not null references users(id) on delete cascade on update cascade,
  primary key (id_users_secretary, id_users_provider)
);

create index if not exists secretaries_provider_idx on secretaries_providers (id_users_provider);

create table if not exists consents (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  created timestamp,
  modified timestamp,
  first_name text,
  last_name text,
  email text,
  ip text,
  type text
);

create table if not exists settings (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  name text,
  value text
);

create index if not exists settings_name_idx on settings (name);
create unique index if not exists settings_id_unique_idx on settings (id);

create table if not exists webhooks (
  id integer generated by default as identity primary key,
  create_datetime timestamp,
  update_datetime timestamp,
  name text,
  url text,
  actions text,
  secret_header text default 'X-Ea-Token',
  secret_token text,
  is_ssl_verified boolean not null default true,
  notes text
);

create table if not exists migrations (
  version bigint primary key
);
create unique index if not exists migrations_version_unique_idx on migrations (version);

insert into roles (
  id,
  create_datetime,
  update_datetime,
  name,
  slug,
  is_admin,
  appointments,
  customers,
  services,
  users,
  system_settings,
  user_settings,
  webhooks,
  blocked_periods
)
values
  (1, null, null, 'Administrator', 'admin', true, 15, 15, 15, 15, 15, 15, 15, 15),
  (2, null, null, 'Provider', 'provider', true, 15, 15, 15, 15, 15, 15, null, null),
  (3, null, null, 'Customer', 'customer', false, 0, 0, 0, 0, 0, 0, 0, 0),
  (4, null, null, 'Secretary', 'secretary', false, 15, 15, 0, 0, 0, 15, 0, 0),
  (5, null, null, 'Admin Provider', 'admin-provider', true, 15, 15, 15, 15, 15, 15, null, null)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  is_admin = excluded.is_admin,
  appointments = excluded.appointments,
  customers = excluded.customers,
  services = excluded.services,
  users = excluded.users,
  system_settings = excluded.system_settings,
  user_settings = excluded.user_settings,
  webhooks = excluded.webhooks,
  blocked_periods = excluded.blocked_periods;

insert into migrations (version)
values (62)
on conflict (version) do nothing;

insert into settings (
  id,
  create_datetime,
  update_datetime,
  name,
  value
)
values
  (1, null, null, 'company_working_plan', '{"monday":{"start":"09:00","end":"23:55","breaks":[{"start":"14:30","end":"15:00"}]},"tuesday":{"start":"09:00","end":"23:55","breaks":[{"start":"14:30","end":"15:00"}]},"wednesday":{"start":"09:00","end":"23:55","breaks":[{"start":"14:30","end":"15:00"}]},"thursday":{"start":"09:00","end":"23:55","breaks":[{"start":"14:30","end":"15:00"}]},"friday":{"start":"09:00","end":"23:55","breaks":[{"start":"14:30","end":"15:00"}]},"saturday":{"start":"09:00","end":"23:55","breaks":[{"start":"14:30","end":"15:00"}]},"sunday":{"start":"09:00","end":"23:55","breaks":[{"start":"14:30","end":"15:00"}]}}'),
  (2, null, null, 'book_advance_timeout', '30'),
  (71, null, null, 'company_name', 'Limbo Health'),
  (72, null, null, 'company_email', 'admin@limbohealth.com'),
  (73, null, null, 'company_link', 'https://limbohealth.com')
on conflict (id) do update
set
  name = excluded.name,
  value = excluded.value;
